[package]
name = "rocksdb-bench"
version = "0.1.0"
authors = ["laizy <aochyi@126.com>"]

[dependencies]
rocksdb = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
sha2 = "*"
rand = "0.5"

[profile.release]
debug = true